### ISSUE TITLE
[Feature] Commit action retention from v1.

### ISSUE THREAD

**Issue by Maverick099** [Coders-Asylum/Bots#61]
V1 bot could commit data to the current repository branch and PR.

## Tasks: 
- [ ]  Cretate data classes.
- [ ]  Create a function to commit a piece of text to a file or blob.
- [ ]  Functionality to create a branch or directly commit depending on the input.
- [ ] Tests
   - [ ] Unit tests
   - [ ] Integration test using the [Fuzzy train](https://github.com/Coders-Asylum/fuzzy-train)
